# Generated by Django 5.2.4 on 2025-07-14 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=200)),
                ('dataInizio', models.DateTimeField(verbose_name='date published')),
                ('tema', models.CharField(max_length=50)),
                ('luogo', models.CharField(max_length=50)),
                ('durata_ore', models.IntegerField(default=0)),
                ('durata_minuti', models.IntegerField(default=0)),
                ('maxPartecipanti', models.IntegerField(default=0)),
                ('locandina', models.TextField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'in approvazione'), (2, 'approvato'), (3, 'rifiutato')], default=1)),
                ('iscritti', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventi',
            },
        ),
    ]
