# Generated by Django 5.2.4 on 2025-07-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='locandina',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
