# Generated by Django 5.2.4 on 2025-07-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0004_remove_evento_iscritti_prenotazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenotazione',
            old_name='user',
            new_name='utente',
        ),
    ]
