# Generated by Django 5.2.4 on 2025-07-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0006_notifica_segnalazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creatore',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.IntegerField(choices=[(1, 'in approvazione'), (2, 'approvato'), (3, 'rifiutato'), (4, 'annullato'), (5, 'svolto'), (6, 'non svolto')], default=1),
        ),
    ]
