# Generated by Django 5.2.4 on 2025-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0007_evento_creatore_alter_evento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segnalazione',
            name='data_segnalazione',
        ),
        migrations.RemoveField(
            model_name='segnalazione',
            name='motivazione',
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='testo_segnalazione',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='titolo',
            field=models.CharField(default='titolo', max_length=50),
        ),
    ]
