# Generated by Django 5.2.4 on 2025-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0008_remove_segnalazione_data_segnalazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='titolo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
