# Generated by Django 5.2.3 on 2025-07-18 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0009_alter_segnalazione_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='locandina',
            field=models.FileField(blank=True, upload_to='locandine/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
